#!/usr/bin/env python3
"""
vibesec - Security guardrails for vibe-coded apps

Usage:
  vibesec init [--tool <tool>] [--stack <stack>]
  vibesec scan [--trivy] [<path>]
  vibesec review [--stack <stack>] [--db <db>] [--payments <payments>]
  vibesec --help
  vibesec --version

Commands:
  init      Install security rules into your project
  scan      Run a lightweight security scan on a directory
  review    Generate an AI review prompt for your stack
  hook      Install a pre-commit hook to block vulnerabilities

Options:
  --tool    AI coding tool: cursor, claude-code, windsurf, lovable (default: cursor)
  --stack   Tech stack: nextjs, nextjs-supabase, nextjs-firebase, remix, sveltekit
  --db      Database/backend: supabase, firebase, prisma, drizzle
  --payments  Payment provider: stripe
  --trivy  Also run Trivy filesystem scan
  --help    Show this help message
  --version Show version
"""

import argparse
import json
import os
import re
import shutil
import stat
import subprocess
import sys
from pathlib import Path

__version__ = "0.1.0"

# ---------------------------------------------------------------------------
# Rule templates
# ---------------------------------------------------------------------------

RULES_CURSOR = """\
# VibeSec Security Rules

- Every API route must verify authentication before accessing data.
- For every user-owned resource, verify owner_id matches the current session user.
- Never use SUPABASE_SERVICE_ROLE_KEY or any admin key in client-side code.
- Always verify Stripe webhook signatures with stripe.webhooks.constructEvent.
- Validate all inputs (body, params, query) with a schema library before use.
- Return 403 Forbidden for ownership violations, not 404 or 200.
- File uploads must validate type, size, and filename server-side.
- Never set CORS to allow all origins on authenticated endpoints.
- Add tests for cross-user access denial on every resource endpoint.

See https://github.com/Seongho-Bae/VibeSec for full rules and checklists.
"""

RULES_CLAUDE = """\
## VibeSec Security Guardrails

Apply the following security rules to all code you generate:

1. **Authentication**: Check authentication as the first operation in every API handler.
2. **Authorization**: Verify resource ownership (owner_id === session.user.id) server-side.
3. **Secrets**: Never use NEXT_PUBLIC_ prefix on secret keys or service role keys.
4. **Input validation**: Validate all inputs with Zod or equivalent before processing.
5. **Stripe**: Always verify webhook signatures before processing payment events.
6. **Supabase**: Use getUser() (not getSession()) server-side; RLS on all tables.
7. **Files**: Validate type, size, and generate server-side filenames for uploads.
8. **CORS**: Restrict to known origins on authenticated endpoints.

Return 401 for unauthenticated requests, 403 for ownership violations.

See https://github.com/Seongho-Bae/VibeSec for full rules and checklists.
"""

RULES_WINDSURF = RULES_CURSOR  # Windsurf uses the same format

CHECKLIST_TEMPLATE = """\
# VibeSec Security Checklist

Generated by vibesec init. Review before launching.

## Authentication
- [ ] All protected routes check authentication server-side
- [ ] Unauthenticated requests return 401
- [ ] Session tokens are stored securely

## Authorization
- [ ] Every resource endpoint verifies ownership (owner_id === session.user.id)
- [ ] Users cannot access each other's data by changing IDs
- [ ] Admin routes are protected by role checks

## Secrets
- [ ] No hardcoded secrets in source code
- [ ] .env files are in .gitignore
- [ ] No NEXT_PUBLIC_ prefix on secret keys

## Database
- [ ] Row Level Security enabled on all user-data tables (Supabase)
- [ ] Firebase rules do not use allow read, write: if true

## Payments
- [ ] Stripe webhook signature verified with constructEvent
- [ ] Prices fetched server-side, not from client request

## Deployment
- [ ] Security headers configured (X-Frame-Options, CSP, etc.)
- [ ] CORS restricted to known origins
- [ ] npm audit clean (no critical/high vulnerabilities)

See https://github.com/Seongho-Bae/VibeSec for full checklists.
"""

# ---------------------------------------------------------------------------
# Scan patterns
# ---------------------------------------------------------------------------

SCAN_RULES = [
    {
        "id": "hardcoded-stripe-secret",
        "pattern": re.compile(r'sk_(?:live|test)_[A-Za-z0-9]{24,}'),
        "severity": "CRITICAL",
        "message": "Hardcoded Stripe secret key detected. Rotate this key immediately. [OWASP A07:2021 - Identification and Authentication Failures]",
        "extensions": None,
    },
    {
        "id": "hardcoded-openai-key",
        "pattern": re.compile(r'sk-[A-Za-z0-9]{32,}'),
        "severity": "CRITICAL",
        "message": "Possible hardcoded OpenAI API key detected. [OWASP A07:2021 - Identification and Authentication Failures]",
        "extensions": None,
    },
    {
        "id": "next-public-secret",
        "pattern": re.compile(
            r'NEXT_PUBLIC_(?:STRIPE_SECRET|SUPABASE_SERVICE_ROLE|DATABASE|JWT_SECRET|NEXTAUTH_SECRET|API_SECRET)',
            re.IGNORECASE,
        ),
        "severity": "CRITICAL",
        "message": "Secret environment variable uses NEXT_PUBLIC_ prefix — this exposes it to the browser bundle. [OWASP A05:2021 - Security Misconfiguration]",
        "extensions": None,
    },
    {
        "id": "supabase-service-role-client",
        "pattern": re.compile(r'NEXT_PUBLIC_.*SERVICE_ROLE', re.IGNORECASE),
        "severity": "CRITICAL",
        "message": "Supabase service role key exposed to the client via NEXT_PUBLIC_ prefix. [OWASP A05:2021 - Security Misconfiguration]",
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".env", ".env.local", ".env.production"],
    },
    {
        "id": "firebase-allow-all",
        "pattern": re.compile(r'allow\s+(?:read|write|read,\s*write)\s*:\s*if\s+true'),
        "severity": "CRITICAL",
        "message": "Firebase/Firestore rule allows unrestricted read/write access. Add authentication and ownership checks. [OWASP A01:2021 - Broken Access Control]",
        "extensions": [".rules"],
    },
    {
        "id": "todo-skip-auth",
        "pattern": re.compile(
            r'(?i)(?:todo|fixme|hack|temp)[^\n]{0,50}(?:auth|security|permission|check|protect)',
        ),
        "severity": "HIGH",
        "message": "Comment suggests auth/security check was deferred. Verify this is not deployed to production. [OWASP A01:2021 - Broken Access Control]",
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".py"],
    },
    {
        "id": "dangerous-cors",
        "pattern": re.compile(r"Access-Control-Allow-Origin['\",\s]*[*]"),
        "severity": "HIGH",
        "message": "CORS set to allow all origins (*). Restrict to known domains. [OWASP A05:2021 - Security Misconfiguration]",
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".py"],
    },
    {
        "id": "hardcoded-database-url",
        "pattern": re.compile(
            r'(?i)(?:DATABASE_URL|POSTGRES_URL)\s*[=:]\s*["\x27](?:postgres|postgresql|mysql)://\S+',
        ),
        "severity": "CRITICAL",
        "message": "Hardcoded database connection string detected. [OWASP A07:2021 - Identification and Authentication Failures]",
        "extensions": None,
    },
    {
        "id": "hardcoded-jwt-secret",
        "pattern": re.compile(
            r'(?i)(?:JWT_SECRET|NEXTAUTH_SECRET)\s*[=:]\s*["\x27][^"\x27\s]{8,}["\x27]',
        ),
        "severity": "CRITICAL",
        "message": "Hardcoded JWT/NextAuth secret detected. [OWASP A02:2021 - Cryptographic Failures]",
        "extensions": None,
    },
    {
        "id": "stripe-webhook-no-verify",
        "pattern": re.compile(r'constructEvent\s*\([^)]*(?:undefined|""|\'\')\s*\)'),
        "severity": "CRITICAL",
        "message": "Stripe constructEvent called with empty/undefined webhook secret. [OWASP A08:2021 - Software and Data Integrity Failures]",
        "extensions": [".ts", ".tsx", ".js", ".jsx"],
    },
    {
        "id": "mock-session-in-handler",
        "pattern": re.compile(
            r'const\s+(?:session|user)\s*=\s*\{\s*(?:user\s*:\s*)?\{\s*id\s*:\s*["\x27]',
        ),
        "severity": "HIGH",
        "message": "Mock or hardcoded session/user object detected in route handler. [OWASP A01:2021 - Broken Access Control]",
        "extensions": [".ts", ".tsx", ".js", ".jsx"],
    },
    {
        "id": "dangerous-eval",
        "pattern": re.compile(r'\beval\s*\('),
        "severity": "CRITICAL",
        "message": "Use of eval() detected. This is a critical risk for arbitrary code execution and injection attacks. [OWASP A03:2021 - Injection]",
        "extensions": [".js", ".jsx", ".ts", ".tsx", ".py"],
    },
    {
        "id": "react-dangerously-set-inner-html",
        "pattern": re.compile(r'dangerouslySetInnerHTML\s*='),
        "severity": "HIGH",
        "message": "Use of dangerouslySetInnerHTML detected. This can lead to Cross-Site Scripting (XSS) if input is not sanitized. [OWASP A03:2021 - Injection]",
        "extensions": [".jsx", ".tsx"],
    },
    {
        "id": "sql-injection-risk",
        "pattern": re.compile(
            r'(?i)(?:query|execute|raw)\s*\(\s*(?:`[^`]*\$\{[^}]+\}[^`]*`|["\'].*?["\']\s*\+\s*[a-zA-Z0-9_]+)'
        ),
        "severity": "CRITICAL",
        "message": "Potential SQL injection detected: string concatenation or template literal in database query. [OWASP A03:2021 - Injection]",
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".py"],
    },
    {
        "id": "node-command-injection",
        "pattern": re.compile(
            r'(?i)\b(?:exec|execSync|spawn|spawnSync)\s*\(\s*(?:`[^`]*\$\{[^}]+\}[^`]*`|["\'].*?["\']\s*\+\s*[a-zA-Z0-9_]+)'
        ),
        "severity": "CRITICAL",
        "message": "Potential Command Injection detected: string concatenation or template literal in child_process execution. [OWASP A03:2021 - Injection]",
        "extensions": [".ts", ".tsx", ".js", ".jsx"],
    },
    {
        "id": "python-command-injection",
        "pattern": re.compile(
            r'(?i)(?:os\.system|subprocess\.(?:Popen|run|call|check_call|check_output))\s*\([^)]*shell\s*=\s*True'
        ),
        "severity": "CRITICAL",
        "message": "Potential Command Injection detected: shell=True used in Python subprocess/os command. [OWASP A03:2021 - Injection]",
        "extensions": [".py"],
    },
    {
        "id": "path-traversal-risk",
        "pattern": re.compile(
            r'(?i)\b(?:fs\.(?:readFile|readFileSync|createReadStream|writeFile|writeFileSync)|open)\s*\(\s*(?:`[^`]*\$\{[^}]+\}[^`]*`|["\'].*?["\']\s*\+\s*[a-zA-Z0-9_]+|f["\'][^"\']*\{[^}]+\}[^"\']*["\'])'
        ),
        "severity": "CRITICAL",
        "message": "Potential Path Traversal detected: dynamic path constructed using template literals, f-strings, or concatenation in file operations. [OWASP A01:2021 - Broken Access Control]",
        "extensions": [".ts", ".tsx", ".js", ".jsx", ".py"],
    },
    {
        "id": "hardcoded-password",
        "pattern": re.compile(
            r'(?i)(?:password|passwd|pwd)\s*[=:]\s*["\x27][^"\x27\s]{6,}["\x27]'
        ),
        "severity": "HIGH",
        "message": "Possible hardcoded password detected. [OWASP A07:2021 - Identification and Authentication Failures]",
        "extensions": None,
    },
]

SKIP_DIRS = {
    ".git", "node_modules", ".next", "dist", "build", ".cache",
    "__pycache__", ".venv", "venv", "env", ".env", "coverage",
}

SKIP_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".woff", ".woff2",
    ".ttf", ".eot", ".mp4", ".mp3", ".zip", ".tar", ".gz", ".lock",
}

NON_BLOCKING_CONTEXTS = {"doc", "test", "example", "scanner-fixture"}

# ---------------------------------------------------------------------------
# Review prompt templates
# ---------------------------------------------------------------------------

REVIEW_PROMPT_BASE = """\
Please perform a security review of this codebase. Focus on vulnerabilities
common in AI-generated web applications.

Review the following areas:

1. **Authentication**: Are there API routes missing auth checks?
2. **Authorization**: Is resource ownership verified server-side for every endpoint?
3. **Secrets**: Are there hardcoded secrets or NEXT_PUBLIC_ on sensitive vars?
4. **Input Validation**: Is user input validated server-side before database operations?
5. **CORS & Headers**: Is CORS restricted? Are security headers configured?
6. **AI Patterns**: Are there TODO comments that defer security checks?
"""

REVIEW_PROMPT_SUPABASE = """\
7. **Supabase RLS**: Is Row Level Security enabled on all user-data tables?
   Do policies use auth.uid() correctly? Is service_role used client-side?
8. **Supabase Auth**: Is getUser() used server-side (not getSession())?
"""

REVIEW_PROMPT_FIREBASE = """\
7. **Firebase Rules**: Are Firestore/Storage rules allowing unrestricted access?
   Is Firebase Admin SDK used only server-side?
"""

REVIEW_PROMPT_STRIPE = """\
9. **Stripe**: Is webhook signature verified with constructEvent?
   Are prices fetched server-side, not from the client? Is billing portal behind auth?
"""

REVIEW_PROMPT_NEXTJS = """\
Stack context: Next.js application.
- Check App Router API routes (app/api/) and server actions for auth gaps.
- Check next.config.js for security headers.
- Verify no secrets use NEXT_PUBLIC_ prefix.
"""

REVIEW_PROMPT_FOOTER = """\

For each issue found, provide:
1. File and location
2. Vulnerability description
3. Risk if exploited
4. Specific code fix
5. Verification test
"""


# ---------------------------------------------------------------------------
# Command implementations
# ---------------------------------------------------------------------------

def cmd_init(args):
    """Install security rules into the project."""
    tool = getattr(args, "tool", "cursor") or "cursor"
    stack = getattr(args, "stack", None)
    project_root = Path(".").resolve()

    installed = []

    tool_configs = {
        "cursor": {
            "path": Path(".cursor") / "rules" / "vibesec.md",
            "content": RULES_CURSOR,
        },
        "claude-code": {
            "path": Path("CLAUDE.md"),
            "content": RULES_CLAUDE,
            "append_marker": "VibeSec",
        },
        "windsurf": {
            "path": Path(".windsurf") / "rules" / "vibesec.md",
            "content": RULES_WINDSURF,
        },
        "lovable": {
            "shared_only": True,
        },
    }

    if tool not in tool_configs:
        print(f"Unknown tool: {tool}")
        print(f"Supported tools: {', '.join(tool_configs.keys())}")
        sys.exit(1)

    config = tool_configs[tool]
    if not config.get("shared_only"):
        target_file = project_root / config["path"]

        # SECURITY: Prevent Arbitrary File Write via symlink path traversal
        if not target_file.resolve().is_relative_to(project_root):
            print(f"Error: Target path {target_file} escapes the project root. Aborting.", file=sys.stderr)
            sys.exit(1)

        target_file.parent.mkdir(parents=True, exist_ok=True)
        if target_file.is_symlink():
            target_file.unlink()

        if "append_marker" in config:
            if target_file.exists():
                existing = target_file.read_text()
                if config["append_marker"] not in existing:
                    target_file.write_text(existing + "\n\n" + config["content"])
                    installed.append(f"{config['path']} (appended)")
                else:
                    print(f"{config['path']} already contains {config['append_marker']} rules — skipping.")
            else:
                target_file.write_text(config["content"])
                installed.append(str(config["path"]))
        else:
            target_file.write_text(config["content"])
            installed.append(str(config["path"]))
    # Always create the checklist
    checklist_file = project_root / "VIBESEC_CHECKLIST.md"

    # SECURITY: Prevent Arbitrary File Write via symlink path traversal
    if not checklist_file.resolve().is_relative_to(project_root):
        print(f"Error: Checklist path {checklist_file} escapes the project root. Aborting.", file=sys.stderr)
        sys.exit(1)

    if checklist_file.is_symlink():
        checklist_file.unlink()
    if not checklist_file.exists():
        checklist_file.write_text(CHECKLIST_TEMPLATE)
        installed.append("VIBESEC_CHECKLIST.md")

    if stack and "supabase" in stack:
        _print_supabase_reminder()

    print("\n✅ VibeSec initialized successfully!\n")
    print("Created/updated files:")
    for f in installed:
        print(f"  {f}")
    print()
    print("Next steps:")
    print("  1. Review the installed rules and customize for your project")
    print("  2. Run 'vibesec scan .' to check for existing issues")
    print("  3. Check VIBESEC_CHECKLIST.md before deploying")
    print()


def _print_supabase_reminder():
    print("\n💡 Supabase stack detected. Quick reminders:")
    print("  - Enable RLS on every user-data table")
    print("  - Use getUser() not getSession() on the server")
    print("  - Keep SUPABASE_SERVICE_ROLE_KEY server-side only")
    print()


def cmd_scan(args):
    """Run a lightweight security scan."""
    scan_arg = Path(getattr(args, "path", ".") or ".")
    scan_path = scan_arg.resolve()
    run_trivy = getattr(args, "trivy", False)

    if not scan_arg.exists():
        print(f"Error: Path does not exist: {scan_path}")
        sys.exit(1)

    if scan_arg.is_symlink():
        print(f"Skipping symlink path: {scan_arg}")
        return 0

    print(f"\n🔍 VibeSec scanning: {scan_path}\n")

    findings = []
    files_scanned = 0

    if scan_path.is_file():
        files_to_scan = [scan_path]
    else:
        files_to_scan = _collect_files(scan_path)

    for file_path in files_to_scan:
        files_scanned += 1
        file_findings = _scan_file(file_path, scan_path)
        findings.extend(file_findings)

    if run_trivy:
        print("🔎 Trivy FS enabled: vuln, secret, misconfig\n")
        try:
            findings.extend(_run_trivy_fs(scan_path))
        except RuntimeError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1

    _print_scan_results(findings, files_scanned)
    return 1 if any(_is_deploy_blocking(f) for f in findings) else 0


def cmd_hook(args):
    """Install a pre-commit hook to block commits with vulnerabilities."""
    project_root = Path(".").resolve()
    git_dir = project_root / ".git"

    if not git_dir.is_dir():
        print("Error: Not a git repository. Run 'git init' first.", file=sys.stderr)
        return 1

    hooks_dir = git_dir / "hooks"
    # SECURITY: Prevent Arbitrary File Write via symlink path traversal
    if not hooks_dir.resolve().is_relative_to(project_root):
        print(f"Error: Target path {hooks_dir} escapes the project root. Aborting.", file=sys.stderr)
        return 1

    hooks_dir.mkdir(parents=True, exist_ok=True)
    pre_commit_file = hooks_dir / "pre-commit"

    if pre_commit_file.is_symlink():
        pre_commit_file.unlink()

    hook_content = """#!/bin/sh
# VibeSec Pre-Commit Hook

echo "\\n🔍 Running VibeSec scan..."
vibesec scan .

if [ $? -ne 0 ]; then
    echo "\\n❌ VibeSec scan failed! Critical or high vulnerabilities found."
    echo "Please fix the issues or use '--no-verify' to bypass (not recommended)."
    exit 1
fi

echo "✅ VibeSec scan passed."
"""

    pre_commit_file.write_text(hook_content)
    pre_commit_file.chmod(pre_commit_file.stat().st_mode | stat.S_IEXEC)

    print("\n✅ VibeSec pre-commit hook installed successfully at .git/hooks/pre-commit!\n")
    print("This will run 'vibesec scan .' before every commit and block commits if vulnerabilities are found.")
    return 0


# ⚡ Bolt: Cache applicable rules per file extension to avoid redundant list
# comprehensions and pre-extract the search method to avoid dictionary and
# attribute lookups in the tight scanning loop.
_RULES_CACHE = {}
_LAST_SCAN_RULES_ID = None

def _get_applicable_rules(ext: str):
    global _LAST_SCAN_RULES_ID, _RULES_CACHE
    current_id = id(SCAN_RULES)
    if _LAST_SCAN_RULES_ID != current_id:
        _RULES_CACHE.clear()
        _LAST_SCAN_RULES_ID = current_id

    if ext not in _RULES_CACHE:
        # ⚡ Bolt: Cache rules as tuples instead of dictionaries. This allows tuple
        # unpacking in the hot scanning loop, bypassing dictionary lookup overhead.
        _RULES_CACHE[ext] = [
            {
                "id": rule["id"],
                "severity": rule["severity"],
                "message": rule["message"],
                "finditer": rule["pattern"].finditer
            }
            for rule in SCAN_RULES
            if not rule["extensions"] or ext in rule["extensions"]
        ]
    return _RULES_CACHE[ext]


def _collect_files(base_path: Path):
    """Collect all scannable files, skipping unwanted directories."""
    # ⚡ Bolt: Optimize file traversal using os.scandir and os.path.splitext
    # This avoids expensive stat() calls by using cached directory attributes
    # and defers Path object creation until a valid file is found.
    # Impact: Significantly faster file discovery in large codebases.
    stack = [str(base_path)]
    while stack:
        current_dir = stack.pop()
        try:
            with os.scandir(current_dir) as it:
                dirs = []
                for entry in it:
                    try:
                        if entry.is_symlink():
                            continue
                        if entry.is_dir(follow_symlinks=False):
                            if entry.name not in SKIP_DIRS and not entry.name.startswith("."):
                                dirs.append(entry.path)
                        elif entry.is_file(follow_symlinks=False):
                            _, ext = os.path.splitext(entry.name)
                            if ext.lower() not in SKIP_EXTENSIONS:
                                yield Path(entry.path)
                    except (OSError, PermissionError):
                        continue
                stack.extend(reversed(dirs))
        except (OSError, PermissionError):
            pass


def _sanitize_terminal_output(text: str) -> str:
    """
    SECURITY: Prevent Terminal Output Injection / ANSI escape sequence injection
    that could hide scanner findings by removing or escaping non-printable characters.
    """
    if not isinstance(text, str):
        return text
    return "".join(c if c.isprintable() or c == '\t' else repr(c)[1:-1] for c in text)


def _finding_context(file_path: str, snippet: str = "") -> str:
    path = (file_path or "").replace("\\", "/").lstrip("./")
    snippet = (snippet or "").strip()
    if path == "README.md" or path.startswith(("docs/", "checklists/", "prompts/")):
        return "doc"
    if path.startswith("tests/") or "/tests/" in path:
        return "test"
    if path.startswith("examples/"):
        return "example"
    if path.startswith("scanner/rules/"):
        return "scanner-fixture"
    if path == "scanner/cli/vibesec.py" and (
        snippet.startswith(('"id":', '"message":', '"pattern":', "r'", 'r"'))
        or "TODO comments that defer" in snippet
    ):
        return "scanner-fixture"
    return "app-code"


def _finding_category(rule_id: str) -> str:
    rule = (rule_id or "").lower()
    if "cve-" in rule or "vulnerability" in rule:
        return "dependency"
    if any(token in rule for token in ("secret", "jwt", "password", "database-url", "openai")):
        return "secrets"
    if "stripe" in rule or "webhook" in rule:
        return "payment"
    if "firebase" in rule or "supabase" in rule or "storage" in rule:
        return "storage"
    if any(token in rule for token in ("auth", "session", "admin")):
        return "authz"
    if any(token in rule for token in ("eval", "sql", "command", "path-traversal")):
        return "injection"
    return "misconfig"


def _confidence(rule_id: str) -> str:
    return "medium" if "todo" in (rule_id or "").lower() else "high"


def _build_finding(source, rule_id, severity, message, file, line, snippet, category=None):
    context = _finding_context(file, snippet)
    category = category or _finding_category(rule_id)
    return {
        "rule_id": rule_id,
        "severity": severity,
        "message": message,
        "file": file,
        "line": line,
        "snippet": _sanitize_terminal_output(snippet),
        "source": source,
        "category": category,
        "confidence": _confidence(rule_id),
        "context": context,
        "fix_prompt": f"Fix {rule_id}: {message}",
        "verification": f"Re-run `vibesec scan` and verify {file}:{line} no longer reports this finding.",
    }


def _is_deploy_blocking(finding: dict) -> bool:
    return (
        finding.get("severity") in ("CRITICAL", "HIGH")
        and finding.get("context", "app-code") not in NON_BLOCKING_CONTEXTS
    )


def _trivy_severity(severity: str) -> str:
    return {
        "CRITICAL": "CRITICAL",
        "HIGH": "HIGH",
        "MEDIUM": "WARNING",
        "LOW": "INFO",
        "UNKNOWN": "INFO",
    }.get((severity or "UNKNOWN").upper(), "INFO")


def _trivy_line(item: dict) -> int:
    metadata = item.get("CauseMetadata") or {}
    return item.get("StartLine") or metadata.get("StartLine") or 1


def _trivy_target(target: str, base_path: Path) -> str:
    if not target:
        return str(base_path)
    try:
        path = Path(target)
        if path.is_absolute():
            root = base_path if base_path.is_dir() else base_path.parent
            return str(path.relative_to(root))
    except ValueError:
        pass
    return target


def _trivy_findings(report: dict, base_path: Path):
    findings = []
    for result in report.get("Results") or []:
        target = _sanitize_terminal_output(_trivy_target(result.get("Target", ""), base_path))

        for vuln in result.get("Vulnerabilities") or []:
            fixed = vuln.get("FixedVersion") or "no fixed version reported"
            findings.append(_build_finding(
                "trivy",
                f"trivy:{vuln.get('VulnerabilityID', 'vulnerability')}",
                _trivy_severity(vuln.get("Severity")),
                f"Trivy vulnerability in {vuln.get('PkgName', 'package')}: {vuln.get('Title') or vuln.get('VulnerabilityID', 'unknown vulnerability')}",
                target,
                1,
                f"{vuln.get('PkgName', 'package')} {vuln.get('InstalledVersion', '')} -> {fixed}".strip(),
                category="dependency",
            ))

        for misconfig in result.get("Misconfigurations") or []:
            findings.append(_build_finding(
                "trivy",
                f"trivy:{misconfig.get('ID', 'misconfiguration')}",
                _trivy_severity(misconfig.get("Severity")),
                f"Trivy misconfiguration: {misconfig.get('Title') or misconfig.get('Message') or misconfig.get('ID', 'misconfiguration')}",
                target,
                _trivy_line(misconfig),
                misconfig.get("Message") or misconfig.get("Description") or "",
                category="misconfig",
            ))

        for secret in result.get("Secrets") or []:
            findings.append(_build_finding(
                "trivy",
                f"trivy:{secret.get('RuleID', 'secret')}",
                _trivy_severity(secret.get("Severity")),
                f"Trivy secret finding: {secret.get('Title') or secret.get('Category') or secret.get('RuleID', 'secret')}",
                target,
                _trivy_line(secret),
                "Trivy secret scanner matched this line; value suppressed.",
                category="secrets",
            ))

    return findings


def _run_trivy_fs(scan_path: Path):
    trivy = shutil.which("trivy")
    if not trivy:
        raise RuntimeError("trivy executable not found. Install Trivy or run without --trivy.")

    process = subprocess.run(
        [
            trivy,
            "fs",
            "--quiet",
            "--format",
            "json",
            "--scanners",
            "vuln,secret,misconfig",
            "--exit-code",
            "0",
            "--no-progress",
            "--skip-version-check",
            str(scan_path),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if process.returncode != 0:
        detail = (process.stderr or process.stdout).strip().splitlines()
        raise RuntimeError("Trivy scan failed" + (f": {detail[-1]}" if detail else "."))

    try:
        report = json.loads(process.stdout or "{}")
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Trivy returned invalid JSON: {exc}") from exc

    return _trivy_findings(report, scan_path)


def _scan_file(file_path: Path, base_path: Path):
    """Scan a single file and return a list of findings."""
    findings = []

    # ⚡ Bolt: Optimize stat calls by using os.lstat instead of Path objects
    # Impact: Combines symlink, file type, and size checks into a single stat call
    try:
        st = os.lstat(file_path)
        # SECURITY: Prevent DoS by skipping special system files (e.g. FIFOs, devices)
        if stat.S_ISLNK(st.st_mode) or not stat.S_ISREG(st.st_mode):
            return findings
        # SECURITY: Prevent OOM by skipping extremely large files
        if st.st_size > 10 * 1024 * 1024:
            return findings
    except (OSError, PermissionError):
        return findings

    ext = file_path.suffix.lower()
    applicable_rules = _get_applicable_rules(ext)

    if not applicable_rules:
        return findings

    # ⚡ Bolt: Defer expensive Pathlib operations (like relative_to) and string
    # sanitization until a match is actually found. This avoids significant overhead
    # for the vast majority of files that have no vulnerabilities.
    rel_path_str = None

    try:
        with file_path.open("r", encoding="utf-8", errors="ignore") as f:
            content = f.read()
            if not content:
                return findings

            for rule in applicable_rules:
                for match in rule["finditer"](content):
                    if rel_path_str is None:
                        rel_path = file_path.relative_to(base_path) if base_path.is_dir() else file_path
                        rel_path_str = _sanitize_terminal_output(str(rel_path))

                    start_idx = match.start()
                    line_num = content.count('\n', 0, start_idx) + 1

                    snippet_start = content.rfind('\n', 0, start_idx) + 1
                    snippet_end = content.find('\n', start_idx)
                    if snippet_end == -1:
                        snippet_end = len(content)
                    snippet = content[snippet_start:snippet_end].strip()[:120]

                    findings.append(_build_finding(
                        "vibesec-rule",
                        rule["id"],
                        rule["severity"],
                        rule["message"],
                        rel_path_str,
                        line_num,
                        snippet,
                    ))
    except (OSError, PermissionError):
        pass

    return findings

def _print_scan_results(findings, files_scanned):
    severity_order = {"CRITICAL": 0, "HIGH": 1, "WARNING": 2, "INFO": 3}
    findings.sort(key=lambda f: severity_order.get(f["severity"], 99))

    severity_icons = {
        "CRITICAL": "🔴 CRITICAL",
        "HIGH": "🟠 HIGH",
        "WARNING": "🟡 WARNING",
        "INFO": "🔵 INFO",
    }

    counts = {"CRITICAL": 0, "HIGH": 0, "WARNING": 0, "INFO": 0}
    non_blocking = 0
    for f in findings:
        if f.get("context", "app-code") not in NON_BLOCKING_CONTEXTS:
            counts[f["severity"]] += 1
        elif f.get("context", "app-code") in NON_BLOCKING_CONTEXTS:
            non_blocking += 1
        icon = severity_icons.get(f["severity"], f["severity"])
        print(f"[{icon}] {f['file']}:{f['line']}")
        print(f"  Rule: {f['rule_id']}")
        print(f"  Source: {f.get('source', 'vibesec-rule')} | Category: {f.get('category', 'misconfig')} | Context: {f.get('context', 'app-code')}")
        print(f"  {f['message']}")
        print(f"  Code: {f['snippet']}")
        if f.get("context", "app-code") in NON_BLOCKING_CONTEXTS:
            print("  Deploy gate: non-blocking context")
        print()

    print("─" * 60)
    print(f"Scanned {files_scanned} files  |  Deploy blockers: "
          f"🔴 {counts['CRITICAL']} critical  "
          f"🟠 {counts['HIGH']} high  "
          f"🟡 {counts['WARNING']} warnings  "
          f"🔵 {counts['INFO']} info")
    if non_blocking:
        print(f"Non-blocking findings in docs/tests/examples/fixtures: {non_blocking}")

    if counts["CRITICAL"] > 0:
        print("\n❌ Critical issues found. Fix before deploying.")
    elif counts["HIGH"] > 0:
        print("\n⚠️  High-severity issues found. Review before deploying.")
    elif not findings:
        print("\n✅ No issues found in this scan.")
    else:
        print("\n✅ No deploy-blocking critical or high issues found.")

    if findings:
        print("\n💡 Run 'vibesec review' to get an AI prompt for fixing these issues.")
    print()


def cmd_review(args):
    """Generate a security review prompt for the given stack."""
    stack = getattr(args, "stack", None)
    db = getattr(args, "db", None)
    payments = getattr(args, "payments", None)

    prompt = REVIEW_PROMPT_BASE

    if stack and "nextjs" in stack:
        prompt += REVIEW_PROMPT_NEXTJS
    if db == "supabase" or (stack and "supabase" in stack):
        prompt += REVIEW_PROMPT_SUPABASE
    if db == "firebase" or (stack and "firebase" in stack):
        prompt += REVIEW_PROMPT_FIREBASE
    if payments == "stripe":
        prompt += REVIEW_PROMPT_STRIPE

    prompt += REVIEW_PROMPT_FOOTER

    print("\n" + "═" * 60)
    print("  VibeSec — Copy this prompt into your AI coding assistant")
    print("═" * 60 + "\n")
    print(prompt)
    print("═" * 60 + "\n")
    print("💡 Tips:")
    print("  - Paste this into Claude Code, Cursor, or any AI assistant")
    print("  - Include relevant files as context (API routes, DB schema, etc.)")
    print("  - Run 'vibesec scan .' first to identify specific files to review")
    print()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        prog="vibesec",
        description="Security guardrails for vibe-coded apps",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")

    subparsers = parser.add_subparsers(dest="command")

    # init
    init_parser = subparsers.add_parser("init", help="Install security rules into your project")
    init_parser.add_argument(
        "--tool",
        choices=["cursor", "claude-code", "windsurf", "lovable"],
        default="cursor",
        help="AI coding tool (default: cursor)",
    )
    init_parser.add_argument(
        "--stack",
        help="Tech stack (e.g. nextjs-supabase, nextjs-firebase)",
    )

    # scan
    scan_parser = subparsers.add_parser("scan", help="Scan a directory for security issues")
    scan_parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Directory or file to scan (default: current directory)",
    )
    scan_parser.add_argument(
        "--trivy",
        action="store_true",
        help="Also run Trivy filesystem scan for dependency, secret, and misconfiguration findings",
    )

    # review
    review_parser = subparsers.add_parser(
        "review", help="Generate an AI security review prompt"
    )
    review_parser.add_argument("--stack", help="Tech stack (e.g. nextjs)")
    review_parser.add_argument("--db", help="Database/backend (e.g. supabase, firebase)")
    review_parser.add_argument("--payments", help="Payment provider (e.g. stripe)")

    # hook
    hook_parser = subparsers.add_parser("hook", help="Install a pre-commit hook to block commits with vulnerabilities")


    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "scan":
        sys.exit(cmd_scan(args))
    elif args.command == "review":
        cmd_review(args)
    elif args.command == "hook":
        sys.exit(cmd_hook(args))
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
