"""Tests for the poetry/pnpm/yarn lockfile parsers (appguardrail_core.sbom)."""

from appguardrail_core.sbom import (
    collect_components,
    parse_pnpm_lock,
    parse_poetry_lock,
    parse_yarn_lock,
)

POETRY_LOCK = """\
# This file is automatically @generated by Poetry and should not be changed.

[[package]]
name = "charset-normalizer"
version = "3.3.2"
description = "The Real First Universal Charset Detector"
optional = false

[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."

[package.dependencies]
charset-normalizer = ">=2,<4"
urllib3 = ">=1.21.1,<3"

[metadata]
lock-version = "2.0"
"""

PNPM_LOCK_V6 = """\
lockfileVersion: '6.0'

packages:

  /lodash@4.17.21:
    resolution: {integrity: sha512-abc}
    dev: false

  /@babel/core@7.23.0(react@18.2.0):
    resolution: {integrity: sha512-def}
    dev: true
"""

PNPM_LOCK_V5 = """\
lockfileVersion: 5.4

packages:
  /react/18.2.0:
    resolution: {integrity: sha512-x}
  /@types/node/20.0.0:
    resolution: {integrity: sha512-y}
"""

YARN_LOCK = """\
# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1

"@babel/core@^7.0.0", "@babel/core@^7.1.0":
  version "7.23.5"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.23.5.tgz"
  integrity sha512-abc

lodash@^4.17.0:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

__metadata:
  version: 6
"""


def test_poetry_lock_resolved(tmp_path):
    (tmp_path / "poetry.lock").write_text(POETRY_LOCK)
    comps = {c["name"]: c for c in parse_poetry_lock(tmp_path / "poetry.lock")}
    assert set(comps) == {"charset-normalizer", "requests"}
    assert comps["charset-normalizer"]["version"] == "3.3.2"
    assert comps["requests"]["version"] == "2.31.0"
    assert comps["requests"]["purl"] == "pkg:pypi/requests@2.31.0"
    assert comps["requests"]["properties"][0]["value"] == "resolved"


def test_pnpm_lock_v6_at_style(tmp_path):
    (tmp_path / "pnpm-lock.yaml").write_text(PNPM_LOCK_V6)
    comps = {c["name"]: c for c in parse_pnpm_lock(tmp_path / "pnpm-lock.yaml")}
    assert comps["lodash"]["version"] == "4.17.21"
    # scoped name preserved, peer-dependency suffix stripped
    assert comps["@babel/core"]["version"] == "7.23.0"
    assert comps["@babel/core"]["purl"] == "pkg:npm/@babel/core@7.23.0"
    assert comps["lodash"]["properties"][0]["value"] == "resolved"


def test_pnpm_lock_v5_slash_style(tmp_path):
    (tmp_path / "pnpm-lock.yaml").write_text(PNPM_LOCK_V5)
    comps = {c["name"]: c for c in parse_pnpm_lock(tmp_path / "pnpm-lock.yaml")}
    assert comps["react"]["version"] == "18.2.0"
    assert comps["@types/node"]["version"] == "20.0.0"
    assert comps["@types/node"]["purl"] == "pkg:npm/@types/node@20.0.0"


def test_yarn_lock_resolved(tmp_path):
    (tmp_path / "yarn.lock").write_text(YARN_LOCK)
    comps = {c["name"]: c for c in parse_yarn_lock(tmp_path / "yarn.lock")}
    assert set(comps) == {"@babel/core", "lodash"}  # __metadata ignored
    assert comps["@babel/core"]["version"] == "7.23.5"
    assert comps["lodash"]["version"] == "4.17.21"
    assert comps["lodash"]["purl"] == "pkg:npm/lodash@4.17.21"
    assert comps["@babel/core"]["properties"][0]["value"] == "resolved"


def test_collect_prefers_pnpm_over_manifest(tmp_path):
    (tmp_path / "package.json").write_text('{"dependencies":{"lodash":"^4.0.0"}}')
    (tmp_path / "pnpm-lock.yaml").write_text(PNPM_LOCK_V6)
    comps = {c["name"]: c for c in collect_components(tmp_path)}
    assert comps["lodash"]["version"] == "4.17.21"  # resolved from pnpm lock
    assert comps["lodash"]["properties"][0]["value"] == "resolved"


def test_collect_prefers_yarn_over_manifest(tmp_path):
    (tmp_path / "package.json").write_text('{"dependencies":{"lodash":"^4.0.0"}}')
    (tmp_path / "yarn.lock").write_text(YARN_LOCK)
    comps = {c["name"]: c for c in collect_components(tmp_path)}
    assert comps["lodash"]["version"] == "4.17.21"
    assert comps["@babel/core"]["properties"][0]["value"] == "resolved"


def test_collect_poetry_is_additive(tmp_path):
    (tmp_path / "requirements.txt").write_text("flask==3.0.0\n")
    (tmp_path / "poetry.lock").write_text(POETRY_LOCK)
    comps = {c["name"]: c for c in collect_components(tmp_path)}
    assert comps["flask"]["version"] == "3.0.0"  # requirements.txt kept
    assert comps["requests"]["version"] == "2.31.0"  # poetry added
    assert comps["charset-normalizer"]["version"] == "3.3.2"
